#' The DamIDResults Class
#'
#' An S4 class to store the results of a damidBind differential analysis,
#' as generated by `differential_binding()` or `differential_accessibility()`.
#'
#' @slot analysis A data.frame containing the full differential analysis table from
#'   limma or NOISeq.
#' @slot upCond1 A data.frame of regions significantly enriched in condition 1.
#' @slot upCond2 A data.frame of regions significantly enriched in condition 2.
#' @slot cond A named character vector mapping user-friendly display names to the
#'   internal condition identifiers used in the analysis.
#' @slot data A list containing the initial input data used for the analysis,
#'   including the occupancy data.frame and other metadata.
#'
#' @name DamIDResults
#' @rdname DamIDResults-class
#' @exportClass DamIDResults
setClass("DamIDResults",
  slots = c(
    analysis = "data.frame",
    upCond1 = "data.frame",
    upCond2 = "data.frame",
    cond = "character",
    data = "list"
  )
)

#' @rdname DamIDResults-class
#' @param object A `DamIDResults` object.
#' @export
setMethod(
  "show", "DamIDResults",
  function(object) {
    cat("An object of class 'DamIDResults'\n")
    cond_display <- names(object@cond)
    cat(sprintf("Differentially %s regions\n", object@data$test_category))
    cat(sprintf("Comparison: '%s' vs '%s'\n", cond_display[1], cond_display[2]))
    cat(sprintf("- %d regions enriched in %s\n", nrow(object@upCond1), cond_display[1]))
    cat(sprintf("- %d regions enriched in %s\n", nrow(object@upCond2), cond_display[2]))
    cat(sprintf("- %d total regions tested\n", nrow(object@analysis)))
    cat("\nAccess results with the '@' accessor, e.g., object@analysis\n")
  }
)
