#' The DamIDResults Class
#'
#' An S4 class to store the results of a damidBind differential analysis,
#' as generated by `differential_binding()` or `differential_accessibility()`.
#'
#' @slot analysis A data.frame containing the full differential analysis table from
#'   limma or NOISeq.
#' @slot upCond1 A data.frame of regions significantly enriched in condition 1.
#' @slot upCond2 A data.frame of regions significantly enriched in condition 2.
#' @slot cond A named character vector mapping user-friendly display names to the
#'   internal condition identifiers used in the analysis.
#' @slot data A list containing the initial input data used for the analysis,
#'   including the occupancy data.frame and other metadata.
#'
#' @name DamIDResults-class
#' @aliases DamIDResults
#' @exportClass DamIDResults
setClass("DamIDResults",
    slots = c(
        analysis = "data.frame",
        upCond1 = "data.frame",
        upCond2 = "data.frame",
        cond = "character",
        data = "list"
    )
)

#' @rdname DamIDResults-class
#' @param object A `DamIDResults` object.
#' @export
setMethod(
    "show", "DamIDResults",
    function(object) {
        cat("An object of class 'DamIDResults'\n")
        cond_display <- names(object@cond)
        cat(sprintf("Differentially %s regions\n", object@data$test_category))
        cat(sprintf("Comparison: '%s' vs '%s'\n", cond_display[1], cond_display[2]))
        cat(sprintf("- %d regions enriched in %s\n", nrow(object@upCond1), cond_display[1]))
        cat(sprintf("- %d regions enriched in %s\n", nrow(object@upCond2), cond_display[2]))
        cat(sprintf("- %d total regions tested\n", nrow(object@analysis)))
    }
)

#' @rdname DamIDResults-class
#' @section Accessor Functions:
#' These functions provide a convenient way to access the different data slots
#' of a `DamIDResults` object.
#' @param object A `DamIDResults` object.
#' @return
#' \itemize{
#'   \item `analysisTable(object)`: returns a data.frame with the full differential analysis.
#'   \item `enrichedCond1(object)`: returns a data.frame of regions enriched in condition 1.
#'   \item `enrichedCond2(object)`: returns a data.frame of regions enriched in condition 2.
#'   \item `conditionNames(object)`: returns a named character vector mapping display names to internal condition identifiers.
#'   \item `inputData(object)`: returns a list containing the initial input data used for the analysis,
#'                              including the occupancy data.frame and other metadata.
#' }
#' @export
#' @examples
#' # Helper function to create a sample DamIDResults object for examples
#' .generate_accessor_example_results <- function() {
#'     analysis_df <- data.frame(
#'         logFC = c(2, -2), P.Value = c(0.01, 0.01),
#'         row.names = c("chr1:1-100", "chr1:101-200")
#'     )
#'     new("DamIDResults",
#'         analysis = analysis_df,
#'         upCond1 = analysis_df[1, , drop = FALSE],
#'         upCond2 = analysis_df[2, , drop = FALSE],
#'         cond = c("Condition 1" = "C1", "Condition 2" = "C2"),
#'         data = list(test_category = "bound")
#'     )
#' }
#' dummy_results <- .generate_accessor_example_results()
#'
#' # Extract the full analysis table
#' head(analysisTable(dummy_results))
#'
#' # Extract regions enriched in condition 1
#' head(enrichedCond1(dummy_results))
#'
#' # Extract regions enriched in condition 2
#' head(enrichedCond2(dummy_results))
#'
#' # Get the condition names
#' conditionNames(dummy_results)
setGeneric("analysisTable", function(object) standardGeneric("analysisTable"))

#' @rdname DamIDResults-class
setMethod("analysisTable", "DamIDResults", function(object) object@analysis)

#' @rdname DamIDResults-class
#' @export
setGeneric("enrichedCond1", function(object) standardGeneric("enrichedCond1"))

#' @rdname DamIDResults-class
setMethod("enrichedCond1", "DamIDResults", function(object) object@upCond1)

#' @rdname DamIDResults-class
#' @export
setGeneric("enrichedCond2", function(object) standardGeneric("enrichedCond2"))

#' @rdname DamIDResults-class
setMethod("enrichedCond2", "DamIDResults", function(object) object@upCond2)

#' @rdname DamIDResults-class
#' @export
setGeneric("conditionNames", function(object) standardGeneric("conditionNames"))

#' @rdname DamIDResults-class
setMethod("conditionNames", "DamIDResults", function(object) object@cond)

#' @rdname DamIDResults-class
#' @export
setGeneric("inputData", function(object) standardGeneric("inputData"))

#' @rdname DamIDResults-class
setMethod("inputData", "DamIDResults", function(object) object@data)
